### ISSUE TITLE
white boarders in portrait mode

### ISSUE THREAD

**Issue by Littlemac123** [cvzi/ScreenshotTile#283] opened 2023-02-04 21:29 UTC
It is making these white boarders for me when my phone is side ways. Im on samsong s20 FE 5g android 12/13 it happen before I upgraded to 13 as well but now im on 13 still happens

| ![Screenshot_2023-02-04_16-23-16](https://user-images.githubusercontent.com/39867553/216790261-1ddcce4a-8a81-4e6a-8b55-b7d6c283db38.png) | ![Screenshot_2023-01-31_09-04-59](https://user-images.githubusercontent.com/39867553/216790263-12203cbb-877a-473e-8073-1672a8264f02.png) | ![Screenshot_2023-01-23_09-36-40](https://user-images.githubusercontent.com/39867553/216790264-b53a58e5-a172-4942-94b1-d58cc7028f9c.png)
| --- | ---- | ---- |

**Comment by Littlemac123** [comment] 2023-02-04 21:30
OH its transparent ! Lol my simple gallery app shows white

**Comment by cvzi** [comment] 2023-02-05 11:10
I can't reproduce it at the moment. I have some questions to narrow down why it happens:
Which option have you set in the app, "legacy method" or "native method"? 
And are you using the quick settings tile, the floating button or the home button to take screenshots?
Does it also happen on the home screen when no app is opened?

**Comment by cvzi** [comment] 2023-02-05 12:06
Never mind, I found the problem. I will fix it

**Comment by cvzi** [comment] 2023-02-05 12:56
Fixed in version 2.0.7

It could take some time until that version is released though, F-Droid hasn't even build version 2.0.6 yet, which I published 10 days ago 😐

**Comment by cvzi** [comment] 2023-02-11 21:54
It seems something is wrong with the build of the app on F-Droid, so it will take at least a few more days until an update is released.

**Comment by cvzi** [comment] 2023-02-16 19:34
Fixed and published in version 2.0.7

https://github.com/cvzi/ScreenshotTile/releases/tag/v2.0.8

**Closed** 2023-02-16 19:35 UTC
Labels: bug
