### ISSUE TITLE
Floating button moves unpredictably

### ISSUE THREAD

**Issue by foodfan** [cvzi/ScreenshotTile#462] opened 2023-11-03 20:33 UTC
I really enjoy the app but since upgrading to Android 14 on pixel 7 pro, the app has been very buggy, including placement of the floating button, which won't stay where it's put, bouncing to the top of left side of the screen. Please fix.

**Comment by cvzi** [comment] 2023-11-03 21:26
I don't have Android 14 to test it (my phone only has Android 10), so I probably won't be able to fix this any time soon.

**Comment by cvzi** [comment] 2024-06-06 14:39
@foodfan @RKitSeal 
I had a few minutes with a Pixel phone with Android 14 and I did some improvements for the floating button. There is a new release [v2.8.4](https://github.com/cvzi/ScreenshotTile/releases/tag/v2.8.4) available that maybe fixes this problem.

The update is available on F-Droid, it will probably take a few hours/days until the new version is available on Google Play Store.

**Comment by RKitSeal** [comment] 2024-06-07 14:02
I truly appreciate this @cvzi ! 
Fixed on Pixel 6

**Comment by RKitSeal** [comment] 2024-06-10 20:17
@cvzi I can't recall for certain how rotation behaved prior to Android 14 as it isn't part of my common use cases and otherwise wasn't a glaring issue, but this doesn't seem "right" to me:

![Screenshot_20240610-140228.png](https://github.com/cvzi/ScreenshotTile/assets/79415396/a698aa7d-a129-45da-95e6-57d9291feaf5)

![Screenshot_20240610-140234.png](https://github.com/cvzi/ScreenshotTile/assets/79415396/f136a65c-0a0f-4fbe-8641-09fd9ba83113)

I can open a separate issue if this isn't specifically related or if preferred.

**Comment by cvzi** [comment] 2024-06-12 11:09
Thanks for the report!
I think this is by design at the moment, not just Android 14. I don't use rotation and I think the last time I tested it was when I initially added the floating button.
But I agree that this is a problem, especially as it is in your screenshot with the "navigation button". It would be more natural to move the button to the same relative position on the screen after a rotation, especially if the button is at a border/corner.

**Comment by cvzi** [comment] 2024-06-20 12:52
It now remembers the position in portrait and landscape orientation independently, so you can move the floating button into a different position in landscape mode and the portrait mode position is not affected. 

I'll close this issue, please comment or reopen if it is not fixed.

**Closed by cvzi** 2024-06-20 12:52 UTC
Labels: bug
